### ISSUE TITLE
Usage of openjdk images

### ISSUE THREAD

**Issue by aitherios** [rayyildiz/docker-kotlin#2]
I noticed the usage of https://hub.docker.com/r/rayyildiz/java8/~/dockerfile/ where you install oracle's jre instead of openjdk (https://hub.docker.com/_/openjdk/). Is it due to a problem? Or something you found in production? (I was just curious)

**Comment by rayyildiz** [comment]
There are several projects which wants yo use [Oracle JDK](http://www.oracle.com/technetwork/java/javase/downloads/index.html) instead of [OpenJDK](http://openjdk.java.net/) . So this is why both  [Docker Java Image](https://hub.docker.com/r/rayyildiz/java8/)  and  [Docker Kotlin Images](https://hub.docker.com/r/rayyildiz/kotlin/) were built on Oracle JDK.

But contribution for supporting openjdk as a new tag is always welcomed.

Thanks your feedback.

**Comment by aitherios** [comment]
Thanks =]

**Comment by rayyildiz** [comment]
Added ```1.1.4-2-openjdk-jdk8``` and ```1.1.4-2-openjdk-jdk8``` tags  to use openjdk. https://hub.docker.com/r/rayyildiz/kotlin/tags/
